# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js(18) CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Info
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "NPM cache: $(npm config get cache)"
    - run: npm ci
    - run: npm run build
    - run: cp dist/circuit-breaker-worker.js src/
    - run: npm test
    - uses: phoenix-actions/test-reporting@v8
      if: success() || failure()
      id: test-report
      with:
        name: JEST Tests (${{ matrix.node-version }})
        path: junit.xml
        reporter: jest-junit
        token: ${{ secrets.GITHUB_TOKEN }}
